### ISSUE TITLE
项目启动了  home里面的菜单点击都报错

### ISSUE THREAD

**Issue by liukx-kellen** [Laird-Lee/adui-admin-template#1]

**Comment by Laird-Lee** [comment]
在根目录下执行 npm run start 之后应该会有三个服务一起启动的，如下图，是使用了npm-run-all的包实现的，所以应该先在根目录下执行npm install
<img width="479" alt="image" src="https://user-images.githubusercontent.com/51226005/188663926-c399e45b-be4a-49ba-92cf-0c6ad3bcb6fc.png">
进入home页之后的菜单后，在控制台会打印出子应用的生命周期
<img width="1797" alt="image" src="https://user-images.githubusercontent.com/51226005/188664597-7405acad-fdd0-450c-bcc3-9da8707420bd.png">
这个项目暂时没精力搞了，就先私有化了，感谢你的提问

**Comment by Laird-Lee** [comment]
项目暂时关闭
